format = """
$os\
[](bg:#769ff0 fg:#3B4252)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$bun\
$c\
$golang\
$nodejs\
$python\
$ruby\
$rust\
$zig\
[](fg:#212736 bg:#06969A)\
$docker_context\
[ ](fg:#06969A)\
\n$character"""

command_timeout = 5000

# OS segment (icon only, no name)
[os]
disabled = false
format = "[ $symbol ]($style)"
style = "fg:#E5E9F0 bg:#3B4252"

[os.symbols]
AlmaLinux = ""
Alpine = ""
Arch = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Macos = ""     # Apple logo
Manjaro = ""
Mint = ""
NixOS = ""
Pop = ""
Raspbian = ""
Redhat = ""
RockyLinux = ""
Ubuntu = ""
Void = ""
Windows = "󰍲"
openSUSE = ""   # openSUSE chameleon
Solus = "󰠳"      # Solus logo
Unknown = ""

# Directory
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Applications" = " 󰀻 "
"Desktop" = " 󰟀 "
"Movies" = "  "
"Google Drive" = "  "
"Contacts" = " 󰛋 "
"Favorites" = " 󰚝 "
"Users" = "  "
"Videos" = "  "
".config" = "  "
".ssh" = " 󰣀 "
"Github" = "  "
# Git
[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# Toolchains
[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[ruby]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[zig]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# Docker context
[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](fg:#e3e5e5 bg:#06969A)]($style)$path'

# Prompt character on line 2
[character]
success_symbol = "[❯](fg:#a3aed2)"
error_symbol = "[❯](fg:#ff6b6b)"
vicmd_symbol = "[❮](fg:#a3aed2)"
format = "$symbol "

# Optional: sudo indicator
[sudo]
disabled = false
style = "bold red"
symbol = " "
format = "[$symbol]($style) "
allow_windows = false
